import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {IDBFactory} from 'fake-indexeddb';
import {emptyJournal, seedEquipment, newDraft, blankSet, sessionFromDraft, sessionWorkout, importedWorkouts, workoutSignature, attendance, equipmentLabel, dayKey} from '../src/journal-model.js';
import {JournalStore} from '../src/journal-store.js';

// Exercise the actual legacy parser and aggregators without mounting the DOM app.
const source=readFileSync(new URL('../src/app.js',import.meta.url),'utf8');
const constants=source.slice(source.indexOf('const BODY_ORDER'),source.indexOf('const state ='));
const parser=source.slice(source.indexOf('function parseDelimitedLine'),source.indexOf('function renderAll'));
const dates=source.slice(source.indexOf('function startOfDay'),source.indexOf('function formatTon'));
const context=vm.createContext({Date,console});
vm.runInContext(`${constants}\n${parser}\n${dates}\nthis.api={parseAdvagymCsv,parseInBodyCsv,enrichWorkouts,annotateWorkouts};`,context);
const {parseAdvagymCsv,parseInBodyCsv,enrichWorkouts}=context.api;
const csv=`Workout date;Sat Jan 01 2000 00:00:00 GMT+0000\nWorkout name;Test\nExercise name;Machine Chest Press\nExercise time (min);5\nSet;Reps;Weight (kg);Weight (lb);Rest (sec);\n1;10;40;88.18;30;\n2;12;45;99.21;30;`;
function journalWithEquipment() {const j=emptyJournal();seedEquipment(j,parseAdvagymCsv(csv));return j;}
function validDraft(j) {const d=newDraft();d.exercises=[{id:'entry',equipmentId:j.equipment[0].id,gymId:j.equipment[0].gymId,sets:[{...blankSet(),weightKg:'40',reps:'10'}]}];return d;}

test('Life Fitness parser retains strength metrics and notes',()=>{const [w]=parseAdvagymCsv(csv+'\nExercise note;シート位置3');assert.equal(w.metrics.volumeKg,940);assert.equal(w.exercises[0].notes,'シート位置3');assert.equal(w.exercises[0].sets.length,2);});
test('existing sample CSV still parses and enriches',()=>{const text=readFileSync(new URL('../data/sample.csv',import.meta.url),'utf8');const w=parseAdvagymCsv(text);assert.ok(w.length);assert.ok(w.every(x=>Number.isFinite(x.metrics.volumeKg)));});
test('InBody parser keeps date, weight and missing values',()=>{const r=parseInBodyCsv('測定日時,体重,骨格筋量,体脂肪率\n2026/09/01 10:00,70,30,20\n2026/10/01 10:00,69,,19');assert.equal(r.length,2);assert.equal(r[1].weight,69);assert.equal(r[1].skeletalMuscle,null);});
test('invalid CSV produces no sessions',()=>{assert.equal(parseAdvagymCsv('hello,world').length,0);assert.equal(parseInBodyCsv('hello,world').length,0);});
test('CSV cardio values remain unchanged',()=>{const [w]=parseAdvagymCsv('Workout date;2026-09-01\nExercise name;Elliptical\nSet;Distance (m);Distance (miles);Time (sec);Energy (kcal);Rest (sec);\n1;2000;1.24;900;120;0');assert.equal(w.exercises[0].type,'cardio');assert.equal(w.metrics.cardioSeconds,900);assert.equal(w.metrics.cardioDistanceM,2000);});
test('name changes retain stable machine and gym links',()=>{const j=journalWithEquipment();j.gyms.push({id:'gym-a',name:'Old'});j.equipment[0].gymId='gym-a';const session=sessionFromDraft(validDraft(j),j);j.gyms[0].name='New';j.equipment[0].name='New machine';const w=sessionWorkout(session,j);assert.equal(w.exercises[0].gymId,'gym-a');assert.equal(w.exercises[0].equipmentId,j.equipment[0].id);assert.match(w.exercises[0].name,/New machine.*New/);});
test('moving equipment does not move past visits',()=>{const j=journalWithEquipment();j.equipment[0].gymId='gym-a';const s=sessionFromDraft(validDraft(j),j);j.equipment[0].gymId='gym-b';assert.equal(sessionWorkout(s,j).exercises[0].gymId,'gym-a');});
test('CSV names seed once without inventing manufacturers or gyms',()=>{const j=journalWithEquipment();const id=j.equipment[0].id;seedEquipment(j,parseAdvagymCsv(csv));assert.equal(j.equipment.length,1);assert.equal(j.equipment[0].id,id);assert.equal(j.equipment[0].gymId,'');assert.equal(j.equipment[0].manufacturer,'');assert.equal(j.equipment[0].officialName,'');});
test('same name equipment stays distinct',()=>{const j=journalWithEquipment();j.equipment.push({...j.equipment[0],id:'other'});assert.notEqual(equipmentLabel(j.equipment[0],j),equipmentLabel(j.equipment[1],j));});
test('historical CSV location remains unknown after machine assignment',()=>{const j=journalWithEquipment();j.equipment[0].gymId='gym-a';j.imports.push({text:csv});const [w]=importedWorkouts(j,parseAdvagymCsv);assert.equal(w.exercises[0].gymId,'');});
test('overlapping CSV imports deduplicate without changing raw text',()=>{const j=journalWithEquipment();j.imports.push({text:csv},{text:csv+'\n'});const before=JSON.stringify(j.imports);assert.equal(importedWorkouts(j,parseAdvagymCsv).length,1);assert.equal(JSON.stringify(j.imports),before);});
test('excluded manual duplicates stay in raw archive but out of stats',()=>{const j=journalWithEquipment();j.imports.push({text:csv,excluded:[workoutSignature(parseAdvagymCsv(csv)[0])]});assert.equal(importedWorkouts(j,parseAdvagymCsv).length,0);assert.equal(j.imports[0].text,csv);});
test('manual strength values feed original chart aggregation',()=>{const j=journalWithEquipment();const w=sessionWorkout(sessionFromDraft(validDraft(j),j),j);enrichWorkouts([w]);assert.equal(w.metrics.volumeKg,400);assert.equal(w.exercises[0].metrics.topWeightKg,40);});
test('assisted machine suppresses 1RM, zero bodyweight is valid',()=>{const j=journalWithEquipment();j.equipment[0].loadMode='assist';const d=validDraft(j);d.exercises[0].sets[0].weightKg='0';const w=sessionWorkout(sessionFromDraft(d,j),j);assert.equal(w.exercises[0].sets[0].e1rmKg,null);assert.equal(w.exercises[0].sets[0].weightKg,0);});
test('empty, negative, fractional reps and future records rejected',()=>{const j=journalWithEquipment();for(const reps of ['', '-1', '1.5']){const d=validDraft(j);d.exercises[0].sets[0].reps=reps;assert.throws(()=>sessionFromDraft(d,j));}const d=validDraft(j);d.date='2099-01-01';assert.throws(()=>sessionFromDraft(d,j),/未来/);d.date='2026-02-30';assert.throws(()=>sessionFromDraft(d,j),/記録日/);});
test('long notes and photos survive serialization',()=>{const j=journalWithEquipment();j.equipment[0].notes='長文メモ\n'.repeat(20000);j.equipment[0].photo='data:image/jpeg;base64,QQ==';assert.deepEqual(JSON.parse(JSON.stringify(j)),j);});
test('calendar counts actual days once and keeps multiple and unknown gyms',()=>{const d=dayKey();const w={date:new Date(),exercises:[{sets:[{}],gymId:'a'},{sets:[{}],gymId:'b'},{sets:[{}],gymId:''}]};const result=attendance([w,{...w}, {...w,source:'sample'},{...w,date:new Date('2099-01-01')}]);assert.equal(result.size,1);assert.equal(result.get(d).sessions.length,2);assert.deepEqual([...result.get(d).gyms],['a','b','']);});
test('transaction queue preserves rapid draft updates and reload',async()=>{globalThis.indexedDB=new IDBFactory();const store=await JournalStore.open();await Promise.all(Array.from({length:30},(_,i)=>store.update(j=>{j.draft={...newDraft(),notes:String(i)};})));const reload=await JournalStore.open();assert.equal(reload.value.draft.notes,'29');assert.equal(reload.value.revision,30);store.db.close();reload.db.close();});
test('failed transaction preserves complete prior state',async()=>{globalThis.indexedDB=new IDBFactory();const store=await JournalStore.open();await store.update(j=>j.gyms.push({id:'a',name:'A'}));const before=structuredClone(store.value);await assert.rejects(store.update(j=>{j.gyms=[];throw Error('simulated quota or validation failure');}));assert.deepEqual(store.value,before);const reload=await JournalStore.open();assert.deepEqual(reload.value,before);store.db.close();reload.db.close();});
test('stale tab cannot overwrite another tab',async()=>{globalThis.indexedDB=new IDBFactory();const a=await JournalStore.open(), b=await JournalStore.open();await a.update(j=>j.gyms.push({id:'a',name:'A'}));await assert.rejects(b.update(j=>j.gyms.push({id:'b',name:'B'})),/別タブ/);assert.equal((await a.backupBundle()).journal.gyms.length,1);a.db.close();b.db.close();});
test('backup is atomic with mutation and includes previous complete data',async()=>{globalThis.indexedDB=new IDBFactory();const store=await JournalStore.open();await store.update(j=>j.imports.push({id:'first',text:csv}));await store.update(j=>j.imports.push({id:'second',text:csv+'\n'}),true);const bundle=await store.backupBundle();assert.equal(bundle.journal.imports.length,2);assert.equal(bundle.backups[0].journal.imports.length,1);assert.equal(bundle.backups[0].journal.imports[0].text,csv);store.db.close();});
if(process.env.REAL_WORKOUT_CSV)test('real attached Life Fitness CSV regression (private local fixture)',()=>{const text=readFileSync(process.env.REAL_WORKOUT_CSV,'utf8');const original=parseAdvagymCsv(text);assert.ok(original.length>10);const j=emptyJournal();seedEquipment(j,original);j.imports.push({text});const current=importedWorkouts(j,parseAdvagymCsv);enrichWorkouts(current);assert.equal(current.length,original.length);assert.ok(JSON.stringify(current.map(w=>w.metrics))===JSON.stringify(original.map(w=>w.metrics)), "All parsed metrics must match");assert.equal(j.imports[0].text,text);});
if(process.env.REAL_INBODY_CSV)test('real local InBody CSV regression (read only fixture)',()=>{const records=parseInBodyCsv(readFileSync(process.env.REAL_INBODY_CSV,'utf8'));assert.ok(records.length);assert.ok(records.some(r=>Number.isFinite(r.weight)));});
